### ISSUE TITLE
skips.includes is not a function

### ISSUE THREAD

**Issue by kkeeth** [ysugimoto/resumify#2]
When executed, an error `skips.includes is not a function` occurs.
This issue part is as follows.

```
/path/to/resumify/resumify:166
    if (skips.includes(i.toString())) {
```

my nodejs version is `4.8.3`

**Comment by ysugimoto** [comment]
I'm sorry for breaking compatibility. I've just fixed :D 
And, just released `v0.8.6`. Please update latest version, thanks.
